#!/usr/bin/env bash
# Reproduce this Omarchy setup on a fresh install.
# Every step is an omarchy command or chezmoi; nothing is copied into /etc by hand.
# Idempotent: `omarchy pkg add` skips installed packages, `chezmoi apply` is a no-op when in sync.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
pkgs() { grep -vE '^\s*#|^\s*$' "$1" | tr '\n' ' '; }

echo "==> packages: Arch / Omarchy repos"
# shellcheck disable=SC2046
omarchy pkg add $(pkgs "$here/packages.txt")

echo "==> AUR build hygiene: no leftover makedepends, no -debug split packages"
yay -Y --save --removemake >/dev/null
[[ -f /etc/makepkg.conf.d/no-debug.conf ]] || echo 'OPTIONS+=(!debug)' | sudo tee /etc/makepkg.conf.d/no-debug.conf >/dev/null

echo "==> packages: AUR"
# shellcheck disable=SC2046
omarchy pkg aur add $(pkgs "$here/packages-aur.txt")

echo "==> shell: zsh as login shell, stock oh-my-zsh template when ~/.zshrc is absent"
[[ $(getent passwd "$USER" | cut -d: -f7) == /usr/bin/zsh ]] || chsh -s /usr/bin/zsh
[[ -f ~/.zshrc ]] || cp /usr/share/oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

echo "==> thpm: theme hook that carries the palette into GTK apps (Thunar, xarchiver and friends)"
thpm install --no-ui
thpm enable gtk-css-compat

echo "==> secrets: stored once in the system keyring; ~/.claude/settings.json is rendered from them"
omarchy pkg add chezmoi
for s in github_token gdrive_client_id gdrive_client_secret; do
  chezmoi secret keyring get --service claude --user "$s" >/dev/null 2>&1 ||
    chezmoi secret keyring set --service claude --user "$s"
done

echo "==> dotfiles via chezmoi (asks the per-machine questions once)"
chezmoi init --source "$here" --apply

echo "==> rtk: Claude Code output filter, static musl build from GitHub Releases"
if ! command -v rtk >/dev/null; then
  tmp=$(mktemp -d)
  curl -fsSL -o "$tmp/rtk.tgz" https://github.com/rtk-ai/rtk/releases/latest/download/rtk-x86_64-unknown-linux-musl.tar.gz
  curl -fsSL -o "$tmp/checksums.txt" https://github.com/rtk-ai/rtk/releases/latest/download/checksums.txt
  (cd "$tmp" && awk '/x86_64-unknown-linux-musl/ {print $1"  rtk.tgz"}' checksums.txt | sha256sum -c -)
  mkdir -p ~/.local/bin && tar -xzf "$tmp/rtk.tgz" -C ~/.local/bin rtk && chmod 755 ~/.local/bin/rtk
  rm -rf "$tmp"
fi

if omarchy hw match omen && ! pacman -Q omen-space-git >/dev/null 2>&1; then
  echo "==> omen-space: HP OMEN fan/RGB/MUX daemon, built as a pacman package from a pinned tag"
  omen_tag=2.0.9
  tmp=$(mktemp -d)
  git clone -q --depth 1 -b "$omen_tag" https://github.com/yunusemreyl/omen-space "$tmp"
  # upstream's PKGBUILD tracks main; pin the source to the same tag we cloned.
  # It also builds with --locked while .gitignore excludes Cargo.lock, so no lock file ever
  # exists in the repo and the build aborts; drop the flag (crates resolve at build time).
  sed -i -e "s|^source=(.*)|source=(\"git+https://github.com/yunusemreyl/omen-space.git#tag=$omen_tag\")|" \
         -e "s/ --locked//" "$tmp/PKGBUILD"
  (cd "$tmp" && makepkg -sri --noconfirm)   # -r drops the build deps (rust) afterwards
  rm -rf "$tmp"
fi

echo "==> omarchy defaults"
omarchy default browser chromium
omarchy default terminal foot
omarchy default editor code

echo "==> toolchains declared in ~/.config/mise/config.toml"
mise install

echo "==> vscode extensions"
# --install-extension is idempotent on its own but re-downloads each one; comparing against
# --list-extensions first keeps a re-run cheap. local.omarchy-theme is generated by THPM's
# vscode-local-compat integration, so it is never declared here.
comm -23 <(pkgs "$here/vscode-extensions.txt" | tr ' ' '\n' | grep -v '^$' | LC_ALL=C sort) \
         <(code --list-extensions 2>/dev/null | LC_ALL=C sort) |
  while read -r ext; do code --install-extension "$ext" --force; done

echo "==> web apps kept"
omarchy webapp install WhatsApp https://web.whatsapp.com/ whatsapp

echo "==> themes from git (hand-made ones come with chezmoi)"
while read -r url; do
  omarchy theme install "$url"
done < <(grep -vE '^\s*#|^\s*$' "$here/themes.txt")

echo "==> shell plugins from git"
while read -r url; do
  omarchy plugin add "$url" --enable --yes
done < <(grep -vE '^\s*#|^\s*$' "$here/plugins.txt")

if chezmoi data | jq -e '.hybrid_gpu' >/dev/null 2>&1 && [[ "$(supergfxctl -g 2>/dev/null)" != "Hybrid" ]]; then
  echo "==> hybrid GPU: this machine is not in Hybrid mode. Run:  omarchy toggle hybrid gpu   (reboots)"
fi

cat <<'EOF'

Optional, interactive, run by hand:
  omarchy remove preinstalls      # drops Omarchy's preinstalled apps/webapps; re-run the webapp line above afterwards
EOF

hyprctl reload >/dev/null 2>&1 || true
echo "==> done"
