--ozone-platform-hint=auto
--ignore-gpu-blocklist
--enable-zero-copy
--enable-features=VaapiVideoDecoder,VaapiVideoDecodeLinuxGL
--disable-features=WaylandWpColorManagerV1,UseSkiaGraphite
--disable-gpu-compositing
