# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

# --- System ---
bindd = SUPER, RETURN, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, T, Activity, exec, $terminal -e btop

# --- Desktop ---
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# --- Media ---
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"

# --- Browser ---
bindd = SUPER SHIFT, B, Browser, exec, $browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private

# --- Communication ---
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-or-focus-webapp Calendar "https://calendar.google.com/calendar/u/0/r"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-or-focus-webapp Email "https://gmail.com"
bindd = SUPER SHIFT, W, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

# --- Tools ---
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, T, Google Translate, exec, omarchy-launch-or-focus-webapp Translate "https://translate.google.com/"

# --- Work ---
bindd = SUPER SHIFT, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, G, Github, exec, omarchy-launch-or-focus-webapp Github "https://github.com"
bindd = SUPER SHIFT CTRL, N, Cursor, exec, uwsm-app -- cursor --disable-gpu --disable-gpu-compositing
bindd = SUPER SHIFT CTRL, G, Graphite, exec, omarchy-launch-or-focus-webapp Graphite "https://graphite.dev"

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
