# Extra env variables
# env = MY_GLOBAL_ENV,setting


env = AQ_DRM_DEVICES="/dev/dri/nvidia-gpu:/dev/dri/amd-igpu"
env = AQ_FORCE_LINEAR_BLIT=0
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct
env = OGL_DEDICATED_HW_STATE_PER_CONTEXT,ENABLE_ROBUST
env = WLR_DRM_NO_ATOMIC,1
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1



