# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    allow_tearing = true
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0
    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 2
}

# https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

misc {
    vrr = 1
    vfr = true
    mouse_move_enables_dpms = true
}

cursor {
    no_hardware_cursors = true
    enable_hyprcursor = true
}

# Kanagawa border color
$activeBorderColor = rgb(dcd7ba)
general {
    col.active_border = $activeBorderColor
}
group {
    col.border_active = $activeBorderColor
}

# Kanagawa backdrop is too strong for default opacity
windowrule = opacity 0.98 0.95, match:tag terminal

# Blur waybar background
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar
