[bar/main]
; Inherit common settings
width = ${settings/bar-defaults.width}
height = ${settings/bar-defaults.height}
radius = ${settings/bar-defaults.radius}
foreground = ${settings/bar-defaults.foreground}
line-size = ${settings/bar-defaults.line-size}
border-size = ${settings/bar-defaults.border-size}
border-color = ${settings/bar-defaults.border-color}
padding-left = ${settings/bar-defaults.padding-left}
padding-right = ${settings/bar-defaults.padding-right}
module-margin = ${settings/bar-defaults.module-margin}
font-0 = ${settings/bar-defaults.font-0}
font-1 = ${settings/bar-defaults.font-1}
cursor-click = ${settings/bar-defaults.cursor-click}
cursor-scroll = ${settings/bar-defaults.cursor-scroll}
enable-ipc = ${settings/bar-defaults.enable-ipc}

; Bar-specific settings
monitor = ${env:MONITOR}
background = ${colors.top-background}
fixed-center = true

modules-left = i3
modules-center = date
modules-right = systray

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
pin-workspaces = false ; Only show workspaces on the same output as the bar

label-mode-padding = 1
label-mode-foreground = #000000
label-mode-background = ${colors.primary}

label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 1

label-unfocused = %index%
label-unfocused-padding = 1

label-visible = %index%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

label-urgent = %index%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

[module/date]
type = internal/date
interval = 60
date = %Y-%m-%d %H:%M
label = %date%
label-foreground = ${colors.foreground}

[module/systray]
type = internal/tray
tray-spacing = 8pt 