[bar/bottom]
; Inherit common settings
width = ${settings/bar-defaults.width}
height = ${settings/bar-defaults.height}
radius = ${settings/bar-defaults.radius}
foreground = ${settings/bar-defaults.foreground}
line-size = ${settings/bar-defaults.line-size}
border-size = ${settings/bar-defaults.border-size}
border-color = ${settings/bar-defaults.border-color}
padding-left = ${settings/bar-defaults.padding-left}
padding-right = ${settings/bar-defaults.padding-right}
module-margin = ${settings/bar-defaults.module-margin}
font-0 = ${settings/bar-defaults.font-0}
font-1 = ${settings/bar-defaults.font-1}
cursor-click = ${settings/bar-defaults.cursor-click}
cursor-scroll = ${settings/bar-defaults.cursor-scroll}
enable-ipc = ${settings/bar-defaults.enable-ipc}

; Bar-specific settings
monitor = ${env:MONITOR}
bottom = true
background = ${colors.bottom-background}
fixed-center = true

modules-right = cpu memory netspeed temperature battery

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.foreground-alt}
format = <label>
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.foreground-alt}
format = <label>
label = %percentage_used%%

[module/battery]
type = internal/battery
battery = BAT0
adapter = ACAD
full-at = 98

format-charging = <animation-charging> <label-charging>
format-charging-prefix = "BAT "
format-charging-prefix-foreground = ${colors.foreground-alt}
label-charging = %percentage%%

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-prefix = "BAT "
format-discharging-prefix-foreground = ${colors.foreground-alt}
label-discharging = %percentage%%

format-full-prefix = "BAT "
format-full-prefix-foreground = ${colors.foreground-alt}
label-full = Full

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.foreground-alt}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.primary}
animation-charging-framerate = 750

[module/netspeed]
type = internal/network
interface = wlo1 # Make sure this is your correct wireless interface
interval = 1
format-connected-prefix = "NET "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = " %upspeed%  %downspeed%"
format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.disabled}

[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
zone-type = acpitz
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input # Verify this path
base-temperature = 20
warn-temperature = 60 