; Main Polybar configuration file
; Include settings, colors, and bar definitions from other files.

include-file = ~/.config/polybar/settings_colors.ini
include-file = ~/.config/polybar/bar_main.ini
include-file = ~/.config/polybar/bar_bottom.ini

; vim:ft=dosini